const defaultFill = '#f2f2f2';

export default const countryDefaults = {
    "AF":{
        fillColor: defaultFill,
        value: ""
    }, "AX":{
        fillColor: defaultFill,
        value: ""
    }, "AL":{
        fillColor: defaultFill,
        value: ""
    }, "DZ":{
        fillColor: defaultFill,
        value: ""
    }, "AS":{
        fillColor: defaultFill,
        value: ""
    }, "AD":{
        fillColor: defaultFill,
        value: ""
    }, "AO":{
        fillColor: defaultFill,
        value: ""
    }, "AI":{
        fillColor: defaultFill,
        value: ""
    }, "AQ":{
        fillColor: defaultFill,
        value: ""
    }, "AG":{
        fillColor: defaultFill,
        value: ""
    }, "AR":{
        fillColor: defaultFill,
        value: ""
    }, "AM":{
        fillColor: defaultFill,
        value: ""
    }, "AW":{
        fillColor: defaultFill,
        value: ""
    }, "AU":{
        fillColor: defaultFill,
        value: ""
    }, "AT":{
        fillColor: defaultFill,
        value: ""
    }, "AZ":{
        fillColor: defaultFill,
        value: ""
    }, "BS":{
        fillColor: defaultFill,
        value: ""
    }, "BH":{
        fillColor: defaultFill,
        value: ""
    }, "BD":{
        fillColor: defaultFill,
        value: ""
    }, "BB":{
        fillColor: defaultFill,
        value: ""
    }, "BY":{
        fillColor: defaultFill,
        value: ""
    }, "BE":{
        fillColor: defaultFill,
        value: ""
    }, "BZ":{
        fillColor: defaultFill,
        value: ""
    }, "BJ":{
        fillColor: defaultFill,
        value: ""
    }, "BM":{
        fillColor: defaultFill,
        value: ""
    }, "BT":{
        fillColor: defaultFill,
        value: ""
    }, "BO":{
        fillColor: defaultFill,
        value: ""
    }, "BQ":{
        fillColor: defaultFill,
        value: ""
    }, "BA":{
        fillColor: defaultFill,
        value: ""
    }, "BW":{
        fillColor: defaultFill,
        value: ""
    }, "BV":{
        fillColor: defaultFill,
        value: ""
    }, "BR":{
        fillColor: defaultFill,
        value: ""
    }, "IO":{
        fillColor: defaultFill,
        value: ""
    }, "UM":{
        fillColor: defaultFill,
        value: ""
    }, "VG":{
        fillColor: defaultFill,
        value: ""
    }, "VI":{
        fillColor: defaultFill,
        value: ""
    }, "BN":{
        fillColor: defaultFill,
        value: ""
    }, "BG":{
        fillColor: defaultFill,
        value: ""
    }, "BF":{
        fillColor: defaultFill,
        value: ""
    }, "BI":{
        fillColor: defaultFill,
        value: ""
    }, "KH":{
        fillColor: defaultFill,
        value: ""
    }, "CM":{
        fillColor: defaultFill,
        value: ""
    }, "CA":{
        fillColor: defaultFill,
        value: ""
    }, "CV":{
        fillColor: defaultFill,
        value: ""
    }, "KY":{
        fillColor: defaultFill,
        value: ""
    }, "CF":{
        fillColor: defaultFill,
        value: ""
    }, "TD":{
        fillColor: defaultFill,
        value: ""
    }, "CL":{
        fillColor: defaultFill,
        value: ""
    }, "CN":{
        fillColor: defaultFill,
        value: ""
    }, "CX":{
        fillColor: defaultFill,
        value: ""
    }, "CC":{
        fillColor: defaultFill,
        value: ""
    }, "CO":{
        fillColor: defaultFill,
        value: ""
    }, "KM":{
        fillColor: defaultFill,
        value: ""
    }, "CG":{
        fillColor: defaultFill,
        value: ""
    }, "CD":{
        fillColor: defaultFill,
        value: ""
    }, "CK":{
        fillColor: defaultFill,
        value: ""
    }, "CR":{
        fillColor: defaultFill,
        value: ""
    }, "HR":{
        fillColor: defaultFill,
        value: ""
    }, "CU":{
        fillColor: defaultFill,
        value: ""
    }, "CW":{
        fillColor: defaultFill,
        value: ""
    }, "CY":{
        fillColor: defaultFill,
        value: ""
    }, "CZ":{
        fillColor: defaultFill,
        value: ""
    }, "DK":{
        fillColor: defaultFill,
        value: ""
    }, "DJ":{
        fillColor: defaultFill,
        value: ""
    }, "DM":{
        fillColor: defaultFill,
        value: ""
    }, "DO":{
        fillColor: defaultFill,
        value: ""
    }, "EC":{
        fillColor: defaultFill,
        value: ""
    }, "EG":{
        fillColor: defaultFill,
        value: ""
    }, "SV":{
        fillColor: defaultFill,
        value: ""
    }, "GQ":{
        fillColor: defaultFill,
        value: ""
    }, "ER":{
        fillColor: defaultFill,
        value: ""
    }, "EE":{
        fillColor: defaultFill,
        value: ""
    }, "ET":{
        fillColor: defaultFill,
        value: ""
    }, "FK":{
        fillColor: defaultFill,
        value: ""
    }, "FO":{
        fillColor: defaultFill,
        value: ""
    }, "FJ":{
        fillColor: defaultFill,
        value: ""
    }, "FI":{
        fillColor: defaultFill,
        value: ""
    }, "FR":{
        fillColor: defaultFill,
        value: ""
    }, "GF":{
        fillColor: defaultFill,
        value: ""
    }, "PF":{
        fillColor: defaultFill,
        value: ""
    }, "TF":{
        fillColor: defaultFill,
        value: ""
    }, "GA":{
        fillColor: defaultFill,
        value: ""
    }, "GM":{
        fillColor: defaultFill,
        value: ""
    }, "GE":{
        fillColor: defaultFill,
        value: ""
    }, "DE":{
        fillColor: defaultFill,
        value: ""
    }, "GH":{
        fillColor: defaultFill,
        value: ""
    }, "GI":{
        fillColor: defaultFill,
        value: ""
    }, "GR":{
        fillColor: defaultFill,
        value: ""
    }, "GL":{
        fillColor: defaultFill,
        value: ""
    }, "GD":{
        fillColor: defaultFill,
        value: ""
    }, "GP":{
        fillColor: defaultFill,
        value: ""
    }, "GU":{
        fillColor: defaultFill,
        value: ""
    }, "GT":{
        fillColor: defaultFill,
        value: ""
    }, "GG":{
        fillColor: defaultFill,
        value: ""
    }, "GW":{
        fillColor: defaultFill,
        value: ""
    }, "GY":{
        fillColor: defaultFill,
        value: ""
    }, "HT":{
        fillColor: defaultFill,
        value: ""
    }, "HM":{
        fillColor: defaultFill,
        value: ""
    }, "VA":{
        fillColor: defaultFill,
        value: ""
    }, "HN":{
        fillColor: defaultFill,
        value: ""
    }, "HK":{
        fillColor: defaultFill,
        value: ""
    }, "HU":{
        fillColor: defaultFill,
        value: ""
    }, "IS":{
        fillColor: defaultFill,
        value: ""
    }, "IN":{
        fillColor: defaultFill,
        value: ""
    }, "ID":{
        fillColor: defaultFill,
        value: ""
    }, "CI":{
        fillColor: defaultFill,
        value: ""
    }, "IR":{
        fillColor: defaultFill,
        value: ""
    }, "IQ":{
        fillColor: defaultFill,
        value: ""
    }, "IE":{
        fillColor: defaultFill,
        value: ""
    }, "IM":{
        fillColor: defaultFill,
        value: ""
    }, "IL":{
        fillColor: defaultFill,
        value: ""
    }, "IT":{
        fillColor: defaultFill,
        value: ""
    }, "JM":{
        fillColor: defaultFill,
        value: ""
    }, "JP":{
        fillColor: defaultFill,
        value: ""
    }, "JE":{
        fillColor: defaultFill,
        value: ""
    }, "JO":{
        fillColor: defaultFill,
        value: ""
    }, "KZ":{
        fillColor: defaultFill,
        value: ""
    }, "KE":{
        fillColor: defaultFill,
        value: ""
    }, "KI":{
        fillColor: defaultFill,
        value: ""
    }, "KW":{
        fillColor: defaultFill,
        value: ""
    }, "KG":{
        fillColor: defaultFill,
        value: ""
    }, "LA":{
        fillColor: defaultFill,
        value: ""
    }, "LV":{
        fillColor: defaultFill,
        value: ""
    }, "LB":{
        fillColor: defaultFill,
        value: ""
    }, "LS":{
        fillColor: defaultFill,
        value: ""
    }, "LR":{
        fillColor: defaultFill,
        value: ""
    }, "LY":{
        fillColor: defaultFill,
        value: ""
    }, "LI":{
        fillColor: defaultFill,
        value: ""
    }, "LT":{
        fillColor: defaultFill,
        value: ""
    }, "LU":{
        fillColor: defaultFill,
        value: ""
    }, "MO":{
        fillColor: defaultFill,
        value: ""
    }, "MK":{
        fillColor: defaultFill,
        value: ""
    }, "MG":{
        fillColor: defaultFill,
        value: ""
    }, "MW":{
        fillColor: defaultFill,
        value: ""
    }, "MY":{
        fillColor: defaultFill,
        value: ""
    }, "MV":{
        fillColor: defaultFill,
        value: ""
    }, "ML":{
        fillColor: defaultFill,
        value: ""
    }, "MT":{
        fillColor: defaultFill,
        value: ""
    }, "MH":{
        fillColor: defaultFill,
        value: ""
    }, "MQ":{
        fillColor: defaultFill,
        value: ""
    }, "MR":{
        fillColor: defaultFill,
        value: ""
    }, "MU":{
        fillColor: defaultFill,
        value: ""
    }, "YT":{
        fillColor: defaultFill,
        value: ""
    }, "MX":{
        fillColor: defaultFill,
        value: ""
    }, "FM":{
        fillColor: defaultFill,
        value: ""
    }, "MD":{
        fillColor: defaultFill,
        value: ""
    }, "MC":{
        fillColor: defaultFill,
        value: ""
    }, "MN":{
        fillColor: defaultFill,
        value: ""
    }, "ME":{
        fillColor: defaultFill,
        value: ""
    }, "MS":{
        fillColor: defaultFill,
        value: ""
    }, "MA":{
        fillColor: defaultFill,
        value: ""
    }, "MZ":{
        fillColor: defaultFill,
        value: ""
    }, "MM":{
        fillColor: defaultFill,
        value: ""
    }, "NA":{
        fillColor: defaultFill,
        value: ""
    }, "NR":{
        fillColor: defaultFill,
        value: ""
    }, "NP":{
        fillColor: defaultFill,
        value: ""
    }, "NL":{
        fillColor: defaultFill,
        value: ""
    }, "NC":{
        fillColor: defaultFill,
        value: ""
    }, "NZ":{
        fillColor: defaultFill,
        value: ""
    }, "NI":{
        fillColor: defaultFill,
        value: ""
    }, "NE":{
        fillColor: defaultFill,
        value: ""
    }, "NG":{
        fillColor: defaultFill,
        value: ""
    }, "NU":{
        fillColor: defaultFill,
        value: ""
    }, "NF":{
        fillColor: defaultFill,
        value: ""
    }, "KP":{
        fillColor: defaultFill,
        value: ""
    }, "MP":{
        fillColor: defaultFill,
        value: ""
    }, "NO":{
        fillColor: defaultFill,
        value: ""
    }, "OM":{
        fillColor: defaultFill,
        value: ""
    }, "PK":{
        fillColor: defaultFill,
        value: ""
    }, "PW":{
        fillColor: defaultFill,
        value: ""
    }, "PS":{
        fillColor: defaultFill,
        value: ""
    }, "PA":{
        fillColor: defaultFill,
        value: ""
    }, "PG":{
        fillColor: defaultFill,
        value: ""
    }, "PY":{
        fillColor: defaultFill,
        value: ""
    }, "PE":{
        fillColor: defaultFill,
        value: ""
    }, "PH":{
        fillColor: defaultFill,
        value: ""
    }, "PN":{
        fillColor: defaultFill,
        value: ""
    }, "PL":{
        fillColor: defaultFill,
        value: ""
    }, "PT":{
        fillColor: defaultFill,
        value: ""
    }, "PR":{
        fillColor: defaultFill,
        value: ""
    }, "QA":{
        fillColor: defaultFill,
        value: ""
    }, "XK":{
        fillColor: defaultFill,
        value: ""
    }, "RE":{
        fillColor: defaultFill,
        value: ""
    }, "RO":{
        fillColor: defaultFill,
        value: ""
    }, "RU":{
        fillColor: defaultFill,
        value: ""
    }, "RW":{
        fillColor: defaultFill,
        value: ""
    }, "BL":{
        fillColor: defaultFill,
        value: ""
    }, "SH":{
        fillColor: defaultFill,
        value: ""
    }, "KN":{
        fillColor: defaultFill,
        value: ""
    }, "LC":{
        fillColor: defaultFill,
        value: ""
    }, "MF":{
        fillColor: defaultFill,
        value: ""
    }, "PM":{
        fillColor: defaultFill,
        value: ""
    }, "VC":{
        fillColor: defaultFill,
        value: ""
    }, "WS":{
        fillColor: defaultFill,
        value: ""
    }, "SM":{
        fillColor: defaultFill,
        value: ""
    }, "ST":{
        fillColor: defaultFill,
        value: ""
    }, "SA":{
        fillColor: defaultFill,
        value: ""
    }, "SN":{
        fillColor: defaultFill,
        value: ""
    }, "RS":{
        fillColor: defaultFill,
        value: ""
    }, "SC":{
        fillColor: defaultFill,
        value: ""
    }, "SL":{
        fillColor: defaultFill,
        value: ""
    }, "SG":{
        fillColor: defaultFill,
        value: ""
    }, "SX":{
        fillColor: defaultFill,
        value: ""
    }, "SK":{
        fillColor: defaultFill,
        value: ""
    }, "SI":{
        fillColor: defaultFill,
        value: ""
    }, "SB":{
        fillColor: defaultFill,
        value: ""
    }, "SO":{
        fillColor: defaultFill,
        value: ""
    }, "ZA":{
        fillColor: defaultFill,
        value: ""
    }, "GS":{
        fillColor: defaultFill,
        value: ""
    }, "KR":{
        fillColor: defaultFill,
        value: ""
    }, "SS":{
        fillColor: defaultFill,
        value: ""
    }, "ES":{
        fillColor: defaultFill,
        value: ""
    }, "LK":{
        fillColor: defaultFill,
        value: ""
    }, "SD":{
        fillColor: defaultFill,
        value: ""
    }, "SR":{
        fillColor: defaultFill,
        value: ""
    }, "SJ":{
        fillColor: defaultFill,
        value: ""
    }, "SZ":{
        fillColor: defaultFill,
        value: ""
    }, "SE":{
        fillColor: defaultFill,
        value: ""
    }, "CH":{
        fillColor: defaultFill,
        value: ""
    }, "SY":{
        fillColor: defaultFill,
        value: ""
    }, "TW":{
        fillColor: defaultFill,
        value: ""
    }, "TJ":{
        fillColor: defaultFill,
        value: ""
    }, "TZ":{
        fillColor: defaultFill,
        value: ""
    }, "TH":{
        fillColor: defaultFill,
        value: ""
    }, "TL":{
        fillColor: defaultFill,
        value: ""
    }, "TG":{
        fillColor: defaultFill,
        value: ""
    }, "TK":{
        fillColor: defaultFill,
        value: ""
    }, "TO":{
        fillColor: defaultFill,
        value: ""
    }, "TT":{
        fillColor: defaultFill,
        value: ""
    }, "TN":{
        fillColor: defaultFill,
        value: ""
    }, "TR":{
        fillColor: defaultFill,
        value: ""
    }, "TM":{
        fillColor: defaultFill,
        value: ""
    }, "TC":{
        fillColor: defaultFill,
        value: ""
    }, "TV":{
        fillColor: defaultFill,
        value: ""
    }, "UG":{
        fillColor: defaultFill,
        value: ""
    }, "UA":{
        fillColor: defaultFill,
        value: ""
    }, "AE":{
        fillColor: defaultFill,
        value: ""
    }, "GB":{
        fillColor: defaultFill,
        value: ""
    }, "US":{
        fillColor: defaultFill,
        value: ""
    }, "UY":{
        fillColor: defaultFill,
        value: ""
    }, "UZ":{
        fillColor: defaultFill,
        value: ""
    }, "VU":{
        fillColor: defaultFill,
        value: ""
    }, "VE":{
        fillColor: defaultFill,
        value: ""
    }, "VN":{
        fillColor: defaultFill,
        value: ""
    }, "WF":{
        fillColor: defaultFill,
        value: ""
    }, "EH":{
        fillColor: defaultFill,
        value: ""
    }, "YE":{
        fillColor: defaultFill,
        value: ""
    }, "ZM":{
        fillColor: defaultFill,
        value: ""
    }, "ZW":{
        fillColor: defaultFill,
        value: ""
    }
};